name: BUILD-NINTENDO_WII-ROM

on:
  push:
   paths:
   - '.github/workflows/build-wii-rom.yml'
   - '240psuite/Wii/**'
  pull_request:
   paths:
   - '.github/workflows/build-wii-rom.yml'
   - '240psuite/Wii/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build tools
      run: |
        cd ./240psuite/Wii/240pSuite/tools
        # build cfile binary and ensure it is at this path.

    - name: Build ROM
      run: |
        cd ./240psuite/Wii/240pSuite
        make -f Makefile.wii

    - name: "Upload built ROMs to artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: NINTENDO_WII-ROM
        path: |
          ${{ github.workspace }}/**/240psuite/Wii/*.dol
