name: BUILD-SEGA_DREAMCAST-ROM

on:
  push:
    paths:
    - '.github/workflows/build-dreamcast-rom.yml'
    - '240psuite/Dreamcast/**'
  pull_request:
    paths:
    - '.github/workflows/build-dreamcast-rom.yml'
    - '240psuite/Dreamcast/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build ROM
      run: |
        cd ${{ github.workspace }}/240psuite/Dreamcast/PVR/
        make

    - name: "Upload built ROMs to artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: SEGA_DREAMCAST-ROM
        path: |
          ${{ github.workspace }}/**/240psuite/Dreamcast/*.GD-ROM
